### ISSUE TITLE
Comparison of Tencent's AI publications and those by FG500 doesn't not make sense

### ISSUE THREAD

**Issue by ngorluong** [georgetown-cset/parat#255] opened 2024-03-19 18:35 UTC
The Fortune Global 500 AI papers (green) have exceptionally slower than Tencent's and Tencent is part of that group. This doesn't make sense.

**Comment by jmelot** [comment] 2024-03-22 14:26
Duplicate of https://github.com/georgetown-cset/parat/issues/271

**Closed by jmelot** 2024-03-22 14:26 UTC
