### ISSUE TITLE
User fazed by column display glitch on detail view load

### ISSUE THREAD

**Issue by za158** [georgetown-cset/parat#420] opened 2024-06-14 15:25 UTC
When you first load detail view, all of the content appears squished over to the left for a moment. On slower loading connections it can last longer. One of the user testers got thrown off by this.

**Comment by jmelot** [comment] 2024-06-14 15:48
Duplicate of #240 but I'm glad you noted that this also caused issues in user testing

**Closed by jmelot** 2024-06-14 15:48 UTC
