### ISSUE TITLE
S&P 500 has 499 members and Fortune Global 500 has 501 members

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#162] opened 2023-10-31 17:44 UTC
![parat-sp500-has-499-members](https://github.com/georgetown-cset/parat/assets/22353962/9359a420-08bf-4cfc-9d00-6c42826865b2)

![parat-global500-has-501-members](https://github.com/georgetown-cset/parat/assets/22353962/2ed9cfe4-5646-4fb0-badc-f24521956716)

**Comment by jmelot** [comment] 2023-11-02 14:02
@rggelles reassigning to you as I confirmed this is present in `high_resolution_entities.aggregated_organizations`

**Comment by rggelles** [comment] 2023-11-29 15:40
I'm not 100% sure this is a bug. It may have to do with organizations that no longer exist or have split/merged. The consequence of using lists from 1-2 years ago at this point. I will double-check but my memory is there were a few cases like this and we're unlikely to get exactly 500 in either list.

**Comment by rggelles** [comment] 2023-11-30 20:58
Okay, here's the longer story for the S&P 500. There were two companies present that weren't checked correctly, but that's not actually why the number isn't 500. I still have to check the fortune 500. Why does the number not add up to 500? Explanation below:

1. We expect there to be a lot more than 500 companies to start, because 500 companies is what are on the S&P 500 at any one moment. Since we didn't want to sum up a single moment, but rather an entire year, the way we handled the S&P 500 was to include any company that was on the S&P 500 *at some time* in 2020. This is more than 500 companies.
2. This number was then reduced by acquisitions. We include the acquiring company even if it isn't also on the S&P 500 (this was a question we struggled with and if you'd prefer we change this we can), so direct acquisitions don't always change our numbers. However, acquisitions by companies that are already on the S&P 500 do, and there are quite a few of these (my quick count has 8 minimum). Also, some acquisitions reduce the number of listed companies for other reasons, e.g. discovery inc class a and class c becomes just warner bros discovery upon acquisition.

**Comment by brianlove** [comment] 2023-11-30 21:15
That all makes a lot of sense.  I think we should include a quick version of this in a tooltip next to the "Viewing X of Y companies" text, plus a more detailed explanation in the documentation, as I'm sure others will have this same question.

**Comment by rggelles** [comment] 2023-12-01 19:55
This data has now been updated in BigQuery (see staging tables). S&P 500 has 503 companies and Fortune Global 500 has 500. This should be correct.

**Closed** 2023-12-05 21:43 UTC
Labels: bug, data
