### ISSUE TITLE
No country for Deutsche Bank/Bahn/Post

### ISSUE THREAD

**Issue by brianlove** [georgetown-cset/parat#193] opened 2024-01-17 02:21 UTC
Deutsche Bank, Deutsche Bahn, and Deutsche Post DHL Group are present in the PARAT dataset but have no country listed (I'm assuming they should all be Germany?).

<img src="https://github.com/georgetown-cset/parat/assets/22353962/9793810b-d597-4ea4-8521-ec0bd16d92ec" width="500px" />

**Comment by rggelles** [comment] 2024-01-17 16:52
I think this is actually a problem with the conversion script after the data, probably caused by the fact that the previous underlying data was broken and @jmelot put in some after-the-fact fixes in to patch it (see [#47](https://github.com/georgetown-cset/parat/issues/47)).

That is, these now have the country DEU in our underlying data, but before our fixes I think they had the country GER. So the patch is likely breaking them right now. @jmelot would you be able to fix this patch?

**Comment by jmelot** [comment] 2024-03-06 20:52
resolved in the new data

**Closed by jmelot** 2024-03-06 20:52 UTC
Labels: data
