### ISSUE TITLE
Specify number of jobs in each company page

### ISSUE THREAD

**Issue by sonali-sr** [georgetown-cset/parat#238] opened 2024-03-19 18:21 UTC
In the Workforce section for each company, the 'NUMBER' of jobs and 'explanatory text' regarding AI and Tech-Tier 1 jobs needs to be customized.

**Comment by jmelot** [comment] 2024-03-22 14:14
Duplicate of https://github.com/georgetown-cset/parat/issues/215

**Closed by jmelot** 2024-03-22 14:14 UTC
